services:
  proglog:
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: tail -f /dev/null
    volumes:
      - ./:/app
      - pkg:/go/bin
      - pkg:/go/pkg

volumes:
  pkg:
