services:
  proglog:
    build:
      context: .
      dockerfile: ./local.Dockerfile
    entrypoint: tail -f /dev/null
    network_mode: "host"
    volumes:
      - ./:/app
      - pkg:/go/bin
      - pkg:/go/pkg

volumes:
  pkg:
